services:
  frontend:
    container_name: angular-app
    build:
      context: ./frontend/angular-app
    image: angular-app-v1
    ports:
      - "9000:80" 
    networks:
      - app-network 
    depends_on:
      - db-master

  backend:
    container_name: django-app
    build:
      context: ./backend/myproject
    image: django-app-v1
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db-master

  db-master:
    container_name: db-master
    build: 
      context: ./data/PostgreSQLdb/master
    ports:
      - "5432:5432"
    volumes:
      - db-master:/var/lib/postgresql/data
    networks:
      - app-network

  db-replica:
    container_name: db-replica
    build: 
      context: ./data/PostgreSQLdb/replica
    environment:
      REPLICATE_FROM: db-master
    depends_on:
      - db-master
    ports:
      - "5433:5432"
    volumes:
      - db-replica:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-master:
  db-replica:

networks:
  app-network:
    driver: bridge
  