services:
  frontend:
    container_name: angular-app
    build:
      context: ./frontend/angular-app
    image: angular-app-v1
    ports:
      - "9000:80" 
    networks:
      - app-network 
    depends_on:
      - master_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "angular-app"

  backend:
    container_name: django-app
    build:
      context: ./backend/myproject
    image: django-app-v1
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - master_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "django-app"

  ## database services
  master_db:
    container_name: master_db
    restart: always
    build: 
      context: ./data/PostgreSQLdb/master
    ports:
      - "5433:5433"
    volumes:
      - master_db:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "master_db"

  replica_db:
    container_name: replica_db
    restart: always
    build: 
      context: ./data/PostgreSQLdb/replica
    ports:
      - "5434:5433"
    volumes:
      - replica_db:/var/lib/postgresql/data
    networks:
      - app-network
    depends_on:
      - master_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: "replica_db"

  ## log service
  fluentd:
    image: fluent/fluentd:latest
    container_name: fluentd
    volumes:
      - ./data/logs:/output/ ## Log file
      - ./fluentd/conf:/fluentd/etc/ ## Config file
    logging:
      driver: "local"
    ports:
      - "24224:24224"
      - "5140:5140/udp"
    links:
      - elasticsearch
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - app-network

volumes:
  master_db:
  replica_db:

networks:
  app-network:
    driver: bridge
  