# Generated by Django 5.1.2 on 2024-11-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255, unique=True)),
                ('file_size', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
