# Generated by Django 5.1.2 on 2024-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
