# Generated by Django 5.1.2 on 2024-11-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uploadedfiles_filename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfiles',
            table='DescriptionTable',
        ),
    ]
