# Generated by Django 5.1.2 on 2024-11-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadedfiles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfiles',
            table='Salopette',
        ),
    ]
