# Generated by Django 5.1.2 on 2024-11-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_uploadedfiles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfiles',
            table='Desciption_table',
        ),
    ]
